using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace PMNetGen
{
    /// <summary>
    /// 由 proto 模型生成 C# 代码。
    ///
    /// 产出约定：
    /// - 目标语言面为 C# 7.3 + .NET Standard 2.0（Unity 2019.4 上限，决策 D4）：
    ///   不使用 record / init / Span / switch 表达式 / using 声明等新语法。
    /// - 不依赖 Google.Protobuf、不依赖反射，可 AOT 化（决策 D1）。
    /// - 逐字节对齐 protobuf 线格式（决策 D3），对齐依据见 EncodingNotes。
    /// - 输出确定性：字段按字段号升序，保证重复生成的产物逐字节稳定（供 build.bat 的 diff 校验使用）。
    /// </summary>
    internal sealed class CSharpEmitter
    {
        private const string IndentUnit = "    ";

        /// <summary>与 protoc C# 生成代码对齐所依据的事实（已对照 Server/Server/SocketProto.cs 逐条核实）。</summary>
        public const string EncodingNotes =
            "编码对齐依据（对照 protoc 生成的 SocketProto.cs 实测）：\n" +
            "1. 字段按字段号升序写出；\n" +
            "2. tag = (字段号 << 3) | wireType；\n" +
            "3. proto3 默认值（0 / false / 空串 / 空数组 / null 子消息）不写出；\n" +
            "4. float 用 fixed32（wireType 5），double 用 fixed64（wireType 1）；\n" +
            "5. 负 int32 按 int64 符号扩展写成 10 字节 varint；\n" +
            "6. string / bytes / 子消息 / packed repeated 标量 用 length-delimited。";

        private readonly ProtoFile _file;
        private readonly string _namespace;
        private readonly string _sourceProtoPath;
        private readonly string _protoHash;
        private readonly StringBuilder _sb = new StringBuilder(64 * 1024);
        private int _indent;

        public CSharpEmitter(ProtoFile file, string ns, string sourceProtoPath, string protoHash)
        {
            _file = file;
            _namespace = ns;
            _sourceProtoPath = sourceProtoPath;
            _protoHash = protoHash;
        }

        public string Generate()
        {
            _indent = 0;
            EmitFileHeader();

            Open("namespace " + _namespace);
            EmitProtocolInfo();
            EmitEnums();
            EmitMessages();
            EmitSerializers();
            Close();

            return _sb.ToString();
        }

        // ---------------- 文件头 ----------------

        private void EmitFileHeader()
        {
            Line("// <auto-generated>");
            Line("//     本文件由 Tools/PMNetGen 生成，请勿手动修改。");
            Line("//     源文件：" + _sourceProtoPath);
            Line("//     proto 内容哈希（SHA-256）：" + _protoHash);
            Line("//     重新生成：执行 ProtobufAndNotepad/Protobuf/build.bat");
            Line("//     同步校验：build.bat 会以 --check 模式比对，不一致即失败");
            Line("//");
            string[] notes = EncodingNotes.Split('\n');
            for (int i = 0; i < notes.Length; i++)
            {
                Line("//     " + notes[i]);
            }

            Line("// </auto-generated>");
            Line(string.Empty);
            Line("using System;");
            Line("using System.Collections.Generic;");
            Line(string.Empty);
        }

        private void EmitProtocolInfo()
        {
            Comment("生成物元信息，供构建期同步校验与运行期诊断使用。");
            Open("public static class PMProtocolInfo");
            Line("/// <summary>权威 proto 相对路径。</summary>");
            Line("public const string SourceProto = " + Literal(_sourceProtoPath) + ";");
            Line(string.Empty);
            Line("/// <summary>生成时 proto 内容的 SHA-256（行尾归一后计算）。</summary>");
            Line("public const string ProtoHash = " + Literal(_protoHash) + ";");
            Line(string.Empty);
            Line("/// <summary>生成器标识。</summary>");
            Line("public const string GeneratedBy = " + Literal("PMNetGen/1") + ";");
            Close();
            Line(string.Empty);
        }

        // ---------------- 枚举 ----------------

        private void EmitEnums()
        {
            if (_file.Enums.Count == 0)
            {
                return;
            }

            Comment("枚举（proto 原名为避免与 SocketProto 命名空间同名类型冲突，统一加 PM 前缀）。");
            for (int i = 0; i < _file.Enums.Count; i++)
            {
                ProtoEnum e = _file.Enums[i];
                Open("public enum PM" + e.Name);
                for (int j = 0; j < e.Values.Count; j++)
                {
                    ProtoEnumValue v = e.Values[j];
                    Line(Naming.EscapeIfKeyword(v.Name) + " = "
                        + v.Number.ToString(CultureInfo.InvariantCulture) + ",");
                }

                Close();
                Line(string.Empty);
            }
        }

        // ---------------- 消息 DTO ----------------

        private void EmitMessages()
        {
            if (_file.Messages.Count == 0)
            {
                return;
            }

            Comment("消息 DTO：纯数据类，无基类、无反射，可 AOT。");
            for (int i = 0; i < _file.Messages.Count; i++)
            {
                ProtoMessage msg = _file.Messages[i];
                Open("public sealed class " + msg.CsType);

                List<ProtoField> ordered = OrderedFields(msg);
                for (int j = 0; j < ordered.Count; j++)
                {
                    ProtoField f = ordered[j];
                    Comment("proto: " + f.Name + " (field " + f.Number + ")");
                    Line("public " + FieldCsType(f) + " " + f.CsName + InitializerFor(f) + ";");
                    if (j < ordered.Count - 1)
                    {
                        Line(string.Empty);
                    }
                }

                Close();
                Line(string.Empty);
            }
        }

        // ---------------- 序列化器 ----------------

        private void EmitSerializers()
        {
            for (int i = 0; i < _file.Messages.Count; i++)
            {
                ProtoMessage msg = _file.Messages[i];
                Comment(msg.Name + " 的静态序列化器（无反射，可 AOT）。");
                Open("public static class " + msg.CsType + "Serializer");
                EmitFieldTable(msg);
                EmitWriteMethod(msg);
                EmitMergeFromMethod(msg);
                EmitConvenienceMethods(msg);
                Close();
                Line(string.Empty);
            }
        }

        private void EmitFieldTable(ProtoMessage msg)
        {
            Comment("字段描述符表：供复制层与调试工具按字段号查元信息。");
            Open("public static readonly PMNetFieldDesc[] Fields = new PMNetFieldDesc[]");
            List<ProtoField> ordered = OrderedFields(msg);
            for (int i = 0; i < ordered.Count; i++)
            {
                ProtoField f = ordered[i];
                Line("new PMNetFieldDesc("
                    + f.Number.ToString(CultureInfo.InvariantCulture) + ", "
                    + Literal(f.Name) + ", "
                    + "PMWireType." + WireTypeOf(f) + ", "
                    + (f.Repeated ? "true" : "false") + "),");
            }

            Close(";");
            Line(string.Empty);
        }

        private void EmitWriteMethod(ProtoMessage msg)
        {
            Comment("序列化。字段按字段号升序写出，与 protoc 生成的 WriteTo 保持一致。");
            Open("public static void Write(PMNetWriter w, " + msg.CsType + " m)");
            Line("if (m == null)");
            OpenBrace();
            Line("return;");
            Close();
            Line(string.Empty);

            List<ProtoField> ordered = OrderedFields(msg);
            for (int i = 0; i < ordered.Count; i++)
            {
                EmitWriteField(ordered[i]);
            }

            Close();
            Line(string.Empty);
        }

        private void EmitWriteField(ProtoField f)
        {
            string access = "m." + f.CsName;

            if (f.Repeated)
            {
                if (f.Kind == ProtoFieldKind.Message)
                {
                    Open("if (" + access + " != null)");
                    Open("for (int i = 0; i < " + access + ".Count; i++)");
                    Line("PMNetWriter sub = w.RentSubWriter();");
                    Line(f.CsType + "Serializer.Write(sub, " + access + "[i]);");
                    Line("w.WriteSubMessage(" + f.Number + ", sub);");
                    Close();
                    Close();
                }
                else if (f.Packed)
                {
                    Open("if (" + access + " != null && " + access + ".Count > 0)");
                    Line("PMNetWriter packed = w.RentSubWriter();");
                    Open("for (int i = 0; i < " + access + ".Count; i++)");
                    Line("packed." + WriteMethodOf(f) + "(" + WriteArgument(f, access + "[i]") + ");");
                    Close();
                    Line("w.WriteSubMessage(" + f.Number + ", packed);");
                    Close();
                }
                else
                {
                    Open("if (" + access + " != null)");
                    Open("for (int i = 0; i < " + access + ".Count; i++)");
                    Line("w.WriteTag(" + f.Number + ", PMWireType.LengthDelimited);");
                    Line("w." + WriteMethodOf(f) + "(" + WriteArgument(f, access + "[i]") + ");");
                    Close();
                    Close();
                }

                Line(string.Empty);
                return;
            }

            if (f.Kind == ProtoFieldKind.Message)
            {
                Open("if (" + access + " != null)");
                Line("PMNetWriter sub = w.RentSubWriter();");
                Line(f.CsType + "Serializer.Write(sub, " + access + ");");
                Line("w.WriteSubMessage(" + f.Number + ", sub);");
                Close();
                Line(string.Empty);
                return;
            }

            Open("if (" + DefaultCheck(f, access) + ")");
            Line("w.WriteTag(" + f.Number + ", PMWireType." + WireTypeOf(f) + ");");
            Line("w." + WriteMethodOf(f) + "(" + WriteArgument(f, access) + ");");
            Close();
            Line(string.Empty);
        }

        private void EmitMergeFromMethod(ProtoMessage msg)
        {
            Comment("反序列化（合并语义，与 protobuf MergeFrom 一致）。未知字段按 wire type 跳过。");
            Open("public static void MergeFrom(PMNetReader r, " + msg.CsType + " m)");
            Line("if (m == null)");
            OpenBrace();
            Line("return;");
            Close();
            Line(string.Empty);
            Line("int fieldNumber;");
            Line("PMWireType wireType;");
            Open("while (r.ReadTag(out fieldNumber, out wireType))");
            Open("switch (fieldNumber)");

            List<ProtoField> ordered = OrderedFields(msg);
            for (int i = 0; i < ordered.Count; i++)
            {
                ProtoField f = ordered[i];
                Line("case " + f.Number.ToString(CultureInfo.InvariantCulture) + ":");
                OpenBrace();
                EmitReadField(f);
                Line("break;");
                Close();
            }

            Line("default:");
            OpenBrace();
            Line("r.SkipField(wireType);");
            Line("break;");
            Close();

            Close();
            Close();
            Close();
            Line(string.Empty);
        }

        private void EmitReadField(ProtoField f)
        {
            string access = "m." + f.CsName;

            if (f.Repeated)
            {
                if (f.Kind == ProtoFieldKind.Message)
                {
                    Line(f.CsType + " item = new " + f.CsType + "();");
                    Line(f.CsType + "Serializer.MergeFrom(r.ReadSubReader(), item);");
                    Line(access + ".Add(item);");
                    return;
                }

                if (f.Packed)
                {
                    // protobuf 同时接受 packed 与未 packed 两种编码，这里都要能读。
                    Open("if (wireType == PMWireType.LengthDelimited)");
                    Line("PMNetReader sub = r.ReadSubReader();");
                    Open("while (!sub.IsAtEnd)");
                    Line(access + ".Add(" + ReadExpression(f, "sub") + ");");
                    Close();
                    Close();
                    Line("else");
                    OpenBrace();
                    Line(access + ".Add(" + ReadExpression(f, "r") + ");");
                    Close();
                    return;
                }

                Line(access + ".Add(" + ReadExpression(f, "r") + ");");
                return;
            }

            if (f.Kind == ProtoFieldKind.Message)
            {
                Open("if (" + access + " == null)");
                Line(access + " = new " + f.CsType + "();");
                Close();
                Line(f.CsType + "Serializer.MergeFrom(r.ReadSubReader(), " + access + ");");
                return;
            }

            Line(access + " = " + ReadExpression(f, "r") + ";");
        }

        private void EmitConvenienceMethods(ProtoMessage msg)
        {
            Comment("便捷入口：一次性序列化 / 反序列化。");
            Open("public static byte[] ToByteArray(" + msg.CsType + " m)");
            Line("PMNetWriter w = new PMNetWriter();");
            Line("Write(w, m);");
            Line("return w.ToArray();");
            Close();
            Line(string.Empty);

            Open("public static " + msg.CsType + " ParseFrom(byte[] data)");
            Line("return ParseFrom(data, 0, data.Length);");
            Close();
            Line(string.Empty);

            Open("public static " + msg.CsType + " ParseFrom(byte[] data, int offset, int count)");
            Line(msg.CsType + " m = new " + msg.CsType + "();");
            Line("MergeFrom(new PMNetReader(data, offset, count), m);");
            Line("return m;");
            Close();
            Line(string.Empty);
        }

        // ---------------- 映射辅助 ----------------

        private static List<ProtoField> OrderedFields(ProtoMessage msg)
        {
            List<ProtoField> ordered = new List<ProtoField>(msg.Fields);
            ordered.Sort(delegate (ProtoField a, ProtoField b) { return a.Number.CompareTo(b.Number); });
            return ordered;
        }

        private static string FieldCsType(ProtoField f)
        {
            return f.Repeated ? "List<" + f.CsType + ">" : f.CsType;
        }

        private static string InitializerFor(ProtoField f)
        {
            if (f.Repeated)
            {
                return " = new List<" + f.CsType + ">()";
            }

            if (f.Kind == ProtoFieldKind.Scalar && f.Scalar == ProtoScalar.String)
            {
                // protobuf 的 string 字段默认是空串而非 null，这里保持一致以免写出/判定行为分叉。
                return " = string.Empty";
            }

            return string.Empty;
        }

        /// <summary>proto3 默认值判定：等于默认值的字段不写出。</summary>
        private static string DefaultCheck(ProtoField f, string access)
        {
            if (f.Kind == ProtoFieldKind.Enum)
            {
                return "(int)" + access + " != 0";
            }

            switch (f.Scalar)
            {
                case ProtoScalar.Bool:
                    return access;
                case ProtoScalar.String:
                    return "!string.IsNullOrEmpty(" + access + ")";
                case ProtoScalar.Bytes:
                    return access + " != null && " + access + ".Length != 0";
                case ProtoScalar.Float:
                    return access + " != 0f";
                case ProtoScalar.Double:
                    return access + " != 0d";
                default:
                    return access + " != 0";
            }
        }

        private static string WriteMethodOf(ProtoField f)
        {
            if (f.Kind == ProtoFieldKind.Enum)
            {
                return "WriteEnum";
            }

            switch (f.Scalar)
            {
                case ProtoScalar.Double: return "WriteDouble";
                case ProtoScalar.Float: return "WriteFloat";
                case ProtoScalar.Int32: return "WriteInt32";
                case ProtoScalar.Int64: return "WriteInt64";
                case ProtoScalar.UInt32: return "WriteUInt32";
                case ProtoScalar.UInt64: return "WriteUInt64";
                case ProtoScalar.SInt32: return "WriteSInt32";
                case ProtoScalar.SInt64: return "WriteSInt64";
                case ProtoScalar.Fixed32: return "WriteFixed32";
                case ProtoScalar.Fixed64: return "WriteFixed64";
                case ProtoScalar.SFixed32: return "WriteSFixed32";
                case ProtoScalar.SFixed64: return "WriteSFixed64";
                case ProtoScalar.Bool: return "WriteBool";
                case ProtoScalar.String: return "WriteStringValue";
                case ProtoScalar.Bytes: return "WriteBytesValue";
                default: throw new NotSupportedException("未支持的标量类型: " + f.Scalar);
            }
        }

        private static string WriteArgument(ProtoField f, string valueExpression)
        {
            return f.Kind == ProtoFieldKind.Enum ? "(int)" + valueExpression : valueExpression;
        }

        private static string ReadExpression(ProtoField f, string reader)
        {
            if (f.Kind == ProtoFieldKind.Enum)
            {
                return "(PM" + f.TypeName + ")" + reader + ".ReadEnum()";
            }

            switch (f.Scalar)
            {
                case ProtoScalar.Double: return reader + ".ReadDouble()";
                case ProtoScalar.Float: return reader + ".ReadFloat()";
                case ProtoScalar.Int32: return reader + ".ReadInt32()";
                case ProtoScalar.Int64: return reader + ".ReadInt64()";
                case ProtoScalar.UInt32: return reader + ".ReadUInt32()";
                case ProtoScalar.UInt64: return reader + ".ReadUInt64()";
                case ProtoScalar.SInt32: return reader + ".ReadSInt32()";
                case ProtoScalar.SInt64: return reader + ".ReadSInt64()";
                case ProtoScalar.Fixed32: return reader + ".ReadFixed32()";
                case ProtoScalar.Fixed64: return reader + ".ReadFixed64()";
                case ProtoScalar.SFixed32: return reader + ".ReadSFixed32()";
                case ProtoScalar.SFixed64: return reader + ".ReadSFixed64()";
                case ProtoScalar.Bool: return reader + ".ReadBool()";
                case ProtoScalar.String: return reader + ".ReadStringValue()";
                case ProtoScalar.Bytes: return reader + ".ReadBytesValue()";
                default: throw new NotSupportedException("未支持的标量类型: " + f.Scalar);
            }
        }

        private static string WireTypeOf(ProtoField f)
        {
            // 子消息是 length-delimited；枚举是 varint。
            if (f.Kind == ProtoFieldKind.Message)
            {
                return "LengthDelimited";
            }

            if (f.Kind == ProtoFieldKind.Enum)
            {
                return "Varint";
            }

            switch (f.Scalar)
            {
                case ProtoScalar.Double:
                case ProtoScalar.Fixed64:
                case ProtoScalar.SFixed64:
                    return "Fixed64";

                case ProtoScalar.Float:
                case ProtoScalar.Fixed32:
                case ProtoScalar.SFixed32:
                    return "Fixed32";

                case ProtoScalar.String:
                case ProtoScalar.Bytes:
                    return "LengthDelimited";

                default:
                    return "Varint";
            }
        }

        private static string Literal(string value)
        {
            StringBuilder sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            for (int i = 0; i < value.Length; i++)
            {
                char c = value[i];
                if (c == '"' || c == '\\')
                {
                    sb.Append('\\').Append(c);
                }
                else if (c == '\n')
                {
                    sb.Append("\\n");
                }
                else if (c == '\r')
                {
                    sb.Append("\\r");
                }
                else
                {
                    sb.Append(c);
                }
            }

            sb.Append('"');
            return sb.ToString();
        }

        // ---------------- 缩进输出 ----------------
        //
        // 语义约定（避免缩进账目出错）：
        //   Line(text)  在当前缩进写一行，缩进不变
        //   Open(text)  在当前缩进写 text 与 "{"，然后缩进 +1
        //   OpenBrace() 在当前缩进写 "{"，然后缩进 +1（用于 case 块等没有头的块）
        //   Close()     缩进 -1，在当前缩进写 "}"
        //   Close(tail) 缩进 -1，在当前缩进写 "}" + tail（如 "};"）

        private void Line(string text)
        {
            if (text.Length == 0)
            {
                _sb.Append('\n');
                return;
            }

            for (int i = 0; i < _indent; i++)
            {
                _sb.Append(IndentUnit);
            }

            _sb.Append(text).Append('\n');
        }

        private void Open(string text)
        {
            Line(text);
            Line("{");
            _indent++;
        }

        private void OpenBrace()
        {
            Line("{");
            _indent++;
        }

        private void Close()
        {
            _indent--;
            Line("}");
        }

        private void Close(string tail)
        {
            _indent--;
            Line("}" + tail);
        }

        private void Comment(string text)
        {
            Line("// " + text);
        }
    }
}
