// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SocketProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SocketProto {

  /// <summary>Holder for reflection information generated from SocketProto.proto</summary>
  public static partial class SocketProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for SocketProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SocketProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTb2NrZXRQcm90by5wcm90bxILU29ja2V0UHJvdG8i7AQKCE1haW5QYWNr",
            "Ei0KC3JlcXVlc3Rjb2RlGAEgASgOMhguU29ja2V0UHJvdG8uUmVxdWVzdENv",
            "ZGUSKwoKYWN0aW9uY29kZRgCIAEoDjIXLlNvY2tldFByb3RvLkFjdGlvbkNv",
            "ZGUSKwoKcmV0dXJuY29kZRgDIAEoDjIXLlNvY2tldFByb3RvLlJldHVybkNv",
            "ZGUSKQoJbG9naW5wYWNrGAQgASgLMhYuU29ja2V0UHJvdG8uTG9naW5QYWNr",
            "EgsKA3N0chgFIAEoCRInCghyb29tcGFjaxgGIAMoCzIVLlNvY2tldFByb3Rv",
            "LlJvb21QYWNrEiwKC2ZyaWVuZHNwYWNrGAcgAygLMhcuU29ja2V0UHJvdG8u",
            "UGxheWVyUGFjaxItCgx1c2VySW5mb3BhY2sYCCABKAsyFy5Tb2NrZXRQcm90",
            "by5QbGF5ZXJQYWNrEjMKDmZyaWVuZHJvb21wYWNrGAkgAygLMhsuU29ja2V0",
            "UHJvdG8uRnJpZW5kUm9vbVBhY2sSLAoLcGxheWVyc3BhY2sYCiADKAsyFy5T",
            "b2NrZXRQcm90by5QbGF5ZXJQYWNrEicKCGNoYXRwYWNrGAsgASgLMhUuU29j",
            "a2V0UHJvdG8uQ2hhdFBhY2sSNwoQYmF0dGxlcGxheWVycGFjaxgMIAMoCzId",
            "LlNvY2tldFByb3RvLkJhdHRsZVBsYXllclBhY2sSEQoJdGltZXN0YW1wGA4g",
            "ASgDEhIKCnJlcXVlc3RfaWQYECABKAVKBAgNEA5KBAgPEBBSCmJhdHRsZUlu",
            "Zm9SFWJhdHRsZV9uZXRfc2ltX2NvbmZpZyI+CghDaGF0UGFjaxISCgpwbGF5",
            "ZXJuYW1lGAEgASgJEg8KB21lc3NhZ2UYAiABKAkSDQoFc3RhdGUYAyABKAUi",
            "LwoJTG9naW5QYWNrEhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIg",
            "ASgJImEKCFJvb21QYWNrEg4KBnJvb21pZBgBIAEoCRIOCgZtYXhudW0YAiAB",
            "KAUSDgoGY3VybnVtGAMgASgFEiUKBXN0YXRlGAQgASgOMhYuU29ja2V0UHJv",
            "dG8uUm9vbVN0YXRlIoUBChBCYXR0bGVQbGF5ZXJQYWNrEgoKAmlkGAEgASgF",
            "Eg4KBnRlYW1pZBgCIAEoBRIOCgZyb29taWQYAyABKAUSEgoKcGxheWVybmFt",
            "ZRgEIAEoCRIfCgRoZXJvGAUgASgOMhEuU29ja2V0UHJvdG8uSGVybxIQCghi",
            "YXR0bGVpZBgGIAEoBSJnCg5GcmllbmRSb29tUGFjaxIOCgZyb29taWQYASAB",
            "KAkSDgoGbWF4bnVtGAIgASgFEg4KBmN1cm51bRgDIAEoBRIlCgVzdGF0ZRgE",
            "IAEoDjIWLlNvY2tldFByb3RvLlJvb21TdGF0ZSK5AQoKUGxheWVyUGFjaxIQ",
            "Cgh1c2VybmFtZRgBIAEoCRISCgpwbGF5ZXJuYW1lGAIgASgJEgoKAmlkGAMg",
            "ASgFEicKBXN0YXRlGAQgASgOMhguU29ja2V0UHJvdG8uUGxheWVyU3RhdGUS",
            "HwoEaGVybxgFIAEoDjIRLlNvY2tldFByb3RvLkhlcm8SLwoMZmlnaHRwYXR0",
            "ZXJuGAYgASgOMhkuU29ja2V0UHJvdG8uRmlnaHRQYXR0ZXJuKooBCgtSZXF1",
            "ZXN0Q29kZRIPCgtSZXF1ZXN0Tm9uZRAAEggKBFVzZXIQARIICgRSb29tEAIS",
            "CgoGRnJpZW5kEAMSDgoKRnJpZW5kUm9vbRAEEgwKCFBpbmdQb25nEAUSDAoI",
            "TWF0Y2hpbmcQBiIECAcQByIECAgQCCoGQmF0dGxlKgpDbGVhclNlbmNlKqoG",
            "CgpBY3Rpb25Db2RlEg4KCkFjdGlvbk5vbmUQABIJCgVMb2dvbhABEgkKBUxv",
            "Z2luEAISDgoKQ3JlYXRlUm9vbRADEgwKCEZpbmRSb29tEAQSDgoKUGxheWVy",
            "TGlzdBAFEgwKCEpvaW5Sb29tEAYSCAoERXhpdBAHEggKBENoYXQQCBIRCg1B",
            "cGx5QWRkRnJpZW5kEAkSEAoMSW52aXRlRnJpZW5kEAoSDAoIRmluZE5hbWUQ",
            "CxIOCgpVcGRhdGVOYW1lEAwSEwoPQWNjZXB0QWRkRnJpZW5kEA0SEwoPUmVq",
            "ZWN0QWRkRnJpZW5kEA4SEgoORmluZFBsYXllckluZm8QDxITCg9GaW5kRnJp",
            "ZW5kc0luZm8QEBIPCgtGcmllbmRMb2dpbhAREhAKDEZyaWVuZExvZ291dBAS",
            "EhYKEkFjY2VwdEludmF0ZUZyaWVuZBATEhYKElJlamVjdEludmF0ZUZyaWVu",
            "ZBAUEhYKEkNhbmNhbEludmF0ZUZyaWVuZBAVEgwKCEV4aXRSb29tEBYSFQoR",
            "R2V0RnJpZW5kUm9vbUluZm8QFxIICgRQaW5nEBgSCAoEUG9uZxAZEg4KCkNo",
            "YW5nZUhlcm8QGhIaChZVcERhdGVBY3RpdmVGcmllbmRJbmZvEBsSFQoRQWRk",
            "TWF0Y2hpbmdQbGF5ZXIQHBIYChRSZW1vdmVNYXRjaGluZ1BsYXllchAdEhQK",
            "EFN0YXJ0RW50ZXJCYXR0bGUQHiIECB8QKSoLQmF0dGxlUmVhZHkqC0JhdHRs",
            "ZVN0YXJ0KiBCYXR0bGVQdXNoRG93bUFsbEZyYW1lT3BlYXJ0aW9ucyoeQmF0",
            "dGxlUHVzaERvd21QbGF5ZXJPcGVhcnRpb25zKhlDbGllbnRTZW5kQ2xlYXJT",
            "ZW5jZVJlYWR5KhJBbGxDbGVhclNlbmNlUmVhZHkqEkNsaWVudFNlbmRHYW1l",
            "T3ZlcioWQmF0dGxlUHVzaERvd21HYW1lT3ZlcioMQmF0dGxlUmV2aWV3KhdC",
            "YXR0bGVQdXNoRG93bkhpdEV2ZW50cyoVQmF0dGxlU2V0TmV0U2ltQ29uZmln",
            "Kk8KClJldHVybkNvZGUSDgoKUmV0dXJuTm9uZRAAEgsKB1N1Y2NlZWQQARII",
            "CgRGYWlsEAISCwoHTm90Um9vbRADEg0KCUFkZEZyaWVuZBAEKjcKCVJvb21T",
            "dGF0ZRIOCgpSb29tTm9ybWFsEAASDAoIUm9vbUZ1bGwQARIMCghSb29tR2Ft",
            "ZRACKmkKC1BsYXllclN0YXRlEhAKDFBsYXllck9ubGluZRAAEhEKDVBsYXll",
            "ck91dGxpbmUQARIOCgpQbGF5ZXJHYW1lEAISEAoMUGxheWVyT25Sb29tEAMS",
            "EwoPUGxheWVyT25JbnZhdGVkEAQq6wEKBEhlcm8SCQoFWHVlTGkQABIKCgZL",
            "ZUVyVGUQARIKCgZQZWlQZWkQAhIJCgVQYW5OaRADEggKBEJhTGkQBBILCgdH",
            "b25nTml1EAUSCgoGRGFMaUVyEAYSCAoER2VFchAHEgsKB0J1THVvS2UQCBIO",
            "CgpCYW9Qb01haUtlEAkSBwoDQUJvEAoSCAoERGlLZRALEgkKBUJlaVlhEAwS",
            "CAoEVGFMYRANEgsKB01haUtlU2kQDhILCgdTaVBhaUtlEA8SCQoFSGVpWWEQ",
            "EBIJCgVMaUFuZxAREggKBFBhTXUQEhIJCgVSdWlLZRATKiwKDEZpZ2h0UGF0",
            "dGVybhIRCg1CYW9TaGlaaGVuZ0JhEAASCQoFU2hlamkQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SocketProto.RequestCode), typeof(global::SocketProto.ActionCode), typeof(global::SocketProto.ReturnCode), typeof(global::SocketProto.RoomState), typeof(global::SocketProto.PlayerState), typeof(global::SocketProto.Hero), typeof(global::SocketProto.FightPattern), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.MainPack), global::SocketProto.MainPack.Parser, new[]{ "Requestcode", "Actioncode", "Returncode", "Loginpack", "Str", "Roompack", "Friendspack", "UserInfopack", "Friendroompack", "Playerspack", "Chatpack", "Battleplayerpack", "Timestamp", "RequestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.ChatPack), global::SocketProto.ChatPack.Parser, new[]{ "Playername", "Message", "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.LoginPack), global::SocketProto.LoginPack.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.RoomPack), global::SocketProto.RoomPack.Parser, new[]{ "Roomid", "Maxnum", "Curnum", "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.BattlePlayerPack), global::SocketProto.BattlePlayerPack.Parser, new[]{ "Id", "Teamid", "Roomid", "Playername", "Hero", "Battleid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.FriendRoomPack), global::SocketProto.FriendRoomPack.Parser, new[]{ "Roomid", "Maxnum", "Curnum", "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketProto.PlayerPack), global::SocketProto.PlayerPack.Parser, new[]{ "Username", "Playername", "Id", "State", "Hero", "Fightpattern" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RequestCode {
    [pbr::OriginalName("RequestNone")] RequestNone = 0,
    [pbr::OriginalName("User")] User = 1,
    [pbr::OriginalName("Room")] Room = 2,
    [pbr::OriginalName("Friend")] Friend = 3,
    [pbr::OriginalName("FriendRoom")] FriendRoom = 4,
    [pbr::OriginalName("PingPong")] PingPong = 5,
    [pbr::OriginalName("Matching")] Matching = 6,
  }

  public enum ActionCode {
    [pbr::OriginalName("ActionNone")] ActionNone = 0,
    [pbr::OriginalName("Logon")] Logon = 1,
    [pbr::OriginalName("Login")] Login = 2,
    [pbr::OriginalName("CreateRoom")] CreateRoom = 3,
    [pbr::OriginalName("FindRoom")] FindRoom = 4,
    [pbr::OriginalName("PlayerList")] PlayerList = 5,
    [pbr::OriginalName("JoinRoom")] JoinRoom = 6,
    [pbr::OriginalName("Exit")] Exit = 7,
    [pbr::OriginalName("Chat")] Chat = 8,
    [pbr::OriginalName("AplyAddFriend")] AplyAddFriend = 9,
    [pbr::OriginalName("InviteFriend")] InviteFriend = 10,
    [pbr::OriginalName("FindName")] FindName = 11,
    [pbr::OriginalName("UpdateName")] UpdateName = 12,
    [pbr::OriginalName("AcceptAddFriend")] AcceptAddFriend = 13,
    [pbr::OriginalName("RejectAddFriend")] RejectAddFriend = 14,
    [pbr::OriginalName("FindPlayerInfo")] FindPlayerInfo = 15,
    [pbr::OriginalName("FindFriendsInfo")] FindFriendsInfo = 16,
    [pbr::OriginalName("FriendLogin")] FriendLogin = 17,
    [pbr::OriginalName("FriendLogout")] FriendLogout = 18,
    [pbr::OriginalName("AcceptInvateFriend")] AcceptInvateFriend = 19,
    [pbr::OriginalName("RejectInvateFriend")] RejectInvateFriend = 20,
    [pbr::OriginalName("CancalInvateFriend")] CancalInvateFriend = 21,
    [pbr::OriginalName("ExitRoom")] ExitRoom = 22,
    [pbr::OriginalName("GetFriendRoomInfo")] GetFriendRoomInfo = 23,
    [pbr::OriginalName("Ping")] Ping = 24,
    [pbr::OriginalName("Pong")] Pong = 25,
    [pbr::OriginalName("ChangeHero")] ChangeHero = 26,
    [pbr::OriginalName("UpDateActiveFriendInfo")] UpDateActiveFriendInfo = 27,
    [pbr::OriginalName("AddMatchingPlayer")] AddMatchingPlayer = 28,
    [pbr::OriginalName("RemoveMatchingPlayer")] RemoveMatchingPlayer = 29,
    [pbr::OriginalName("StartEnterBattle")] StartEnterBattle = 30,
  }

  public enum ReturnCode {
    [pbr::OriginalName("ReturnNone")] ReturnNone = 0,
    [pbr::OriginalName("Succeed")] Succeed = 1,
    [pbr::OriginalName("Fail")] Fail = 2,
    [pbr::OriginalName("NotRoom")] NotRoom = 3,
    [pbr::OriginalName("AddFriend")] AddFriend = 4,
  }

  public enum RoomState {
    [pbr::OriginalName("RoomNormal")] RoomNormal = 0,
    [pbr::OriginalName("RoomFull")] RoomFull = 1,
    [pbr::OriginalName("RoomGame")] RoomGame = 2,
  }

  public enum PlayerState {
    [pbr::OriginalName("PlayerOnline")] PlayerOnline = 0,
    [pbr::OriginalName("PlayerOutline")] PlayerOutline = 1,
    [pbr::OriginalName("PlayerGame")] PlayerGame = 2,
    [pbr::OriginalName("PlayerOnRoom")] PlayerOnRoom = 3,
    [pbr::OriginalName("PlayerOnInvated")] PlayerOnInvated = 4,
  }

  public enum Hero {
    [pbr::OriginalName("XueLi")] XueLi = 0,
    [pbr::OriginalName("KeErTe")] KeErTe = 1,
    [pbr::OriginalName("PeiPei")] PeiPei = 2,
    [pbr::OriginalName("PanNi")] PanNi = 3,
    [pbr::OriginalName("BaLi")] BaLi = 4,
    [pbr::OriginalName("GongNiu")] GongNiu = 5,
    [pbr::OriginalName("DaLiEr")] DaLiEr = 6,
    [pbr::OriginalName("GeEr")] GeEr = 7,
    [pbr::OriginalName("BuLuoKe")] BuLuoKe = 8,
    [pbr::OriginalName("BaoPoMaiKe")] BaoPoMaiKe = 9,
    [pbr::OriginalName("ABo")] Abo = 10,
    [pbr::OriginalName("DiKe")] DiKe = 11,
    [pbr::OriginalName("BeiYa")] BeiYa = 12,
    [pbr::OriginalName("TaLa")] TaLa = 13,
    [pbr::OriginalName("MaiKeSi")] MaiKeSi = 14,
    [pbr::OriginalName("SiPaiKe")] SiPaiKe = 15,
    [pbr::OriginalName("HeiYa")] HeiYa = 16,
    [pbr::OriginalName("LiAng")] LiAng = 17,
    [pbr::OriginalName("PaMu")] PaMu = 18,
    [pbr::OriginalName("RuiKe")] RuiKe = 19,
  }

  public enum FightPattern {
    [pbr::OriginalName("BaoShiZhengBa")] BaoShiZhengBa = 0,
    [pbr::OriginalName("Sheji")] Sheji = 1,
  }

  #endregion

  #region Messages
  public sealed partial class MainPack : pb::IMessage<MainPack> {
    private static readonly pb::MessageParser<MainPack> _parser = new pb::MessageParser<MainPack>(() => new MainPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MainPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MainPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MainPack(MainPack other) : this() {
      requestcode_ = other.requestcode_;
      actioncode_ = other.actioncode_;
      returncode_ = other.returncode_;
      loginpack_ = other.loginpack_ != null ? other.loginpack_.Clone() : null;
      str_ = other.str_;
      roompack_ = other.roompack_.Clone();
      friendspack_ = other.friendspack_.Clone();
      userInfopack_ = other.userInfopack_ != null ? other.userInfopack_.Clone() : null;
      friendroompack_ = other.friendroompack_.Clone();
      playerspack_ = other.playerspack_.Clone();
      chatpack_ = other.chatpack_ != null ? other.chatpack_.Clone() : null;
      battleplayerpack_ = other.battleplayerpack_.Clone();
      timestamp_ = other.timestamp_;
      requestId_ = other.requestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MainPack Clone() {
      return new MainPack(this);
    }

    /// <summary>Field number for the "requestcode" field.</summary>
    public const int RequestcodeFieldNumber = 1;
    private global::SocketProto.RequestCode requestcode_ = global::SocketProto.RequestCode.RequestNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.RequestCode Requestcode {
      get { return requestcode_; }
      set {
        requestcode_ = value;
      }
    }

    /// <summary>Field number for the "actioncode" field.</summary>
    public const int ActioncodeFieldNumber = 2;
    private global::SocketProto.ActionCode actioncode_ = global::SocketProto.ActionCode.ActionNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.ActionCode Actioncode {
      get { return actioncode_; }
      set {
        actioncode_ = value;
      }
    }

    /// <summary>Field number for the "returncode" field.</summary>
    public const int ReturncodeFieldNumber = 3;
    private global::SocketProto.ReturnCode returncode_ = global::SocketProto.ReturnCode.ReturnNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.ReturnCode Returncode {
      get { return returncode_; }
      set {
        returncode_ = value;
      }
    }

    /// <summary>Field number for the "loginpack" field.</summary>
    public const int LoginpackFieldNumber = 4;
    private global::SocketProto.LoginPack loginpack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.LoginPack Loginpack {
      get { return loginpack_; }
      set {
        loginpack_ = value;
      }
    }

    /// <summary>Field number for the "str" field.</summary>
    public const int StrFieldNumber = 5;
    private string str_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Str {
      get { return str_; }
      set {
        str_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roompack" field.</summary>
    public const int RoompackFieldNumber = 6;
    private static readonly pb::FieldCodec<global::SocketProto.RoomPack> _repeated_roompack_codec
        = pb::FieldCodec.ForMessage(50, global::SocketProto.RoomPack.Parser);
    private readonly pbc::RepeatedField<global::SocketProto.RoomPack> roompack_ = new pbc::RepeatedField<global::SocketProto.RoomPack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SocketProto.RoomPack> Roompack {
      get { return roompack_; }
    }

    /// <summary>Field number for the "friendspack" field.</summary>
    public const int FriendspackFieldNumber = 7;
    private static readonly pb::FieldCodec<global::SocketProto.PlayerPack> _repeated_friendspack_codec
        = pb::FieldCodec.ForMessage(58, global::SocketProto.PlayerPack.Parser);
    private readonly pbc::RepeatedField<global::SocketProto.PlayerPack> friendspack_ = new pbc::RepeatedField<global::SocketProto.PlayerPack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SocketProto.PlayerPack> Friendspack {
      get { return friendspack_; }
    }

    /// <summary>Field number for the "userInfopack" field.</summary>
    public const int UserInfopackFieldNumber = 8;
    private global::SocketProto.PlayerPack userInfopack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.PlayerPack UserInfopack {
      get { return userInfopack_; }
      set {
        userInfopack_ = value;
      }
    }

    /// <summary>Field number for the "friendroompack" field.</summary>
    public const int FriendroompackFieldNumber = 9;
    private static readonly pb::FieldCodec<global::SocketProto.FriendRoomPack> _repeated_friendroompack_codec
        = pb::FieldCodec.ForMessage(74, global::SocketProto.FriendRoomPack.Parser);
    private readonly pbc::RepeatedField<global::SocketProto.FriendRoomPack> friendroompack_ = new pbc::RepeatedField<global::SocketProto.FriendRoomPack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SocketProto.FriendRoomPack> Friendroompack {
      get { return friendroompack_; }
    }

    /// <summary>Field number for the "playerspack" field.</summary>
    public const int PlayerspackFieldNumber = 10;
    private static readonly pb::FieldCodec<global::SocketProto.PlayerPack> _repeated_playerspack_codec
        = pb::FieldCodec.ForMessage(82, global::SocketProto.PlayerPack.Parser);
    private readonly pbc::RepeatedField<global::SocketProto.PlayerPack> playerspack_ = new pbc::RepeatedField<global::SocketProto.PlayerPack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SocketProto.PlayerPack> Playerspack {
      get { return playerspack_; }
    }

    /// <summary>Field number for the "chatpack" field.</summary>
    public const int ChatpackFieldNumber = 11;
    private global::SocketProto.ChatPack chatpack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.ChatPack Chatpack {
      get { return chatpack_; }
      set {
        chatpack_ = value;
      }
    }

    /// <summary>Field number for the "battleplayerpack" field.</summary>
    public const int BattleplayerpackFieldNumber = 12;
    private static readonly pb::FieldCodec<global::SocketProto.BattlePlayerPack> _repeated_battleplayerpack_codec
        = pb::FieldCodec.ForMessage(98, global::SocketProto.BattlePlayerPack.Parser);
    private readonly pbc::RepeatedField<global::SocketProto.BattlePlayerPack> battleplayerpack_ = new pbc::RepeatedField<global::SocketProto.BattlePlayerPack>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SocketProto.BattlePlayerPack> Battleplayerpack {
      get { return battleplayerpack_; }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 14;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 16;
    private int requestId_;
    /// <summary>
    /// 请求关联 ID（计划 P1 / B3）。
    /// 0 表示非请求（服务端主动推送、广播、多播）；非 0 时回包会原样带回，
    /// 供客户端做「回包匹配 + 超时重试去重」。这是 proto3 追加字段，旧端不受影响。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MainPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MainPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Requestcode != other.Requestcode) return false;
      if (Actioncode != other.Actioncode) return false;
      if (Returncode != other.Returncode) return false;
      if (!object.Equals(Loginpack, other.Loginpack)) return false;
      if (Str != other.Str) return false;
      if(!roompack_.Equals(other.roompack_)) return false;
      if(!friendspack_.Equals(other.friendspack_)) return false;
      if (!object.Equals(UserInfopack, other.UserInfopack)) return false;
      if(!friendroompack_.Equals(other.friendroompack_)) return false;
      if(!playerspack_.Equals(other.playerspack_)) return false;
      if (!object.Equals(Chatpack, other.Chatpack)) return false;
      if(!battleplayerpack_.Equals(other.battleplayerpack_)) return false;
      if (Timestamp != other.Timestamp) return false;
      if (RequestId != other.RequestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Requestcode != global::SocketProto.RequestCode.RequestNone) hash ^= Requestcode.GetHashCode();
      if (Actioncode != global::SocketProto.ActionCode.ActionNone) hash ^= Actioncode.GetHashCode();
      if (Returncode != global::SocketProto.ReturnCode.ReturnNone) hash ^= Returncode.GetHashCode();
      if (loginpack_ != null) hash ^= Loginpack.GetHashCode();
      if (Str.Length != 0) hash ^= Str.GetHashCode();
      hash ^= roompack_.GetHashCode();
      hash ^= friendspack_.GetHashCode();
      if (userInfopack_ != null) hash ^= UserInfopack.GetHashCode();
      hash ^= friendroompack_.GetHashCode();
      hash ^= playerspack_.GetHashCode();
      if (chatpack_ != null) hash ^= Chatpack.GetHashCode();
      hash ^= battleplayerpack_.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (RequestId != 0) hash ^= RequestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Requestcode != global::SocketProto.RequestCode.RequestNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Requestcode);
      }
      if (Actioncode != global::SocketProto.ActionCode.ActionNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Actioncode);
      }
      if (Returncode != global::SocketProto.ReturnCode.ReturnNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Returncode);
      }
      if (loginpack_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Loginpack);
      }
      if (Str.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Str);
      }
      roompack_.WriteTo(output, _repeated_roompack_codec);
      friendspack_.WriteTo(output, _repeated_friendspack_codec);
      if (userInfopack_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(UserInfopack);
      }
      friendroompack_.WriteTo(output, _repeated_friendroompack_codec);
      playerspack_.WriteTo(output, _repeated_playerspack_codec);
      if (chatpack_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Chatpack);
      }
      battleplayerpack_.WriteTo(output, _repeated_battleplayerpack_codec);
      if (Timestamp != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(Timestamp);
      }
      if (RequestId != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Requestcode != global::SocketProto.RequestCode.RequestNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Requestcode);
      }
      if (Actioncode != global::SocketProto.ActionCode.ActionNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Actioncode);
      }
      if (Returncode != global::SocketProto.ReturnCode.ReturnNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Returncode);
      }
      if (loginpack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Loginpack);
      }
      if (Str.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Str);
      }
      size += roompack_.CalculateSize(_repeated_roompack_codec);
      size += friendspack_.CalculateSize(_repeated_friendspack_codec);
      if (userInfopack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserInfopack);
      }
      size += friendroompack_.CalculateSize(_repeated_friendroompack_codec);
      size += playerspack_.CalculateSize(_repeated_playerspack_codec);
      if (chatpack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chatpack);
      }
      size += battleplayerpack_.CalculateSize(_repeated_battleplayerpack_codec);
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (RequestId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RequestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MainPack other) {
      if (other == null) {
        return;
      }
      if (other.Requestcode != global::SocketProto.RequestCode.RequestNone) {
        Requestcode = other.Requestcode;
      }
      if (other.Actioncode != global::SocketProto.ActionCode.ActionNone) {
        Actioncode = other.Actioncode;
      }
      if (other.Returncode != global::SocketProto.ReturnCode.ReturnNone) {
        Returncode = other.Returncode;
      }
      if (other.loginpack_ != null) {
        if (loginpack_ == null) {
          Loginpack = new global::SocketProto.LoginPack();
        }
        Loginpack.MergeFrom(other.Loginpack);
      }
      if (other.Str.Length != 0) {
        Str = other.Str;
      }
      roompack_.Add(other.roompack_);
      friendspack_.Add(other.friendspack_);
      if (other.userInfopack_ != null) {
        if (userInfopack_ == null) {
          UserInfopack = new global::SocketProto.PlayerPack();
        }
        UserInfopack.MergeFrom(other.UserInfopack);
      }
      friendroompack_.Add(other.friendroompack_);
      playerspack_.Add(other.playerspack_);
      if (other.chatpack_ != null) {
        if (chatpack_ == null) {
          Chatpack = new global::SocketProto.ChatPack();
        }
        Chatpack.MergeFrom(other.Chatpack);
      }
      battleplayerpack_.Add(other.battleplayerpack_);
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.RequestId != 0) {
        RequestId = other.RequestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Requestcode = (global::SocketProto.RequestCode) input.ReadEnum();
            break;
          }
          case 16: {
            Actioncode = (global::SocketProto.ActionCode) input.ReadEnum();
            break;
          }
          case 24: {
            Returncode = (global::SocketProto.ReturnCode) input.ReadEnum();
            break;
          }
          case 34: {
            if (loginpack_ == null) {
              Loginpack = new global::SocketProto.LoginPack();
            }
            input.ReadMessage(Loginpack);
            break;
          }
          case 42: {
            Str = input.ReadString();
            break;
          }
          case 50: {
            roompack_.AddEntriesFrom(input, _repeated_roompack_codec);
            break;
          }
          case 58: {
            friendspack_.AddEntriesFrom(input, _repeated_friendspack_codec);
            break;
          }
          case 66: {
            if (userInfopack_ == null) {
              UserInfopack = new global::SocketProto.PlayerPack();
            }
            input.ReadMessage(UserInfopack);
            break;
          }
          case 74: {
            friendroompack_.AddEntriesFrom(input, _repeated_friendroompack_codec);
            break;
          }
          case 82: {
            playerspack_.AddEntriesFrom(input, _repeated_playerspack_codec);
            break;
          }
          case 90: {
            if (chatpack_ == null) {
              Chatpack = new global::SocketProto.ChatPack();
            }
            input.ReadMessage(Chatpack);
            break;
          }
          case 98: {
            battleplayerpack_.AddEntriesFrom(input, _repeated_battleplayerpack_codec);
            break;
          }
          case 112: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 128: {
            RequestId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ChatPack : pb::IMessage<ChatPack> {
    private static readonly pb::MessageParser<ChatPack> _parser = new pb::MessageParser<ChatPack>(() => new ChatPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatPack(ChatPack other) : this() {
      playername_ = other.playername_;
      message_ = other.message_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatPack Clone() {
      return new ChatPack(this);
    }

    /// <summary>Field number for the "playername" field.</summary>
    public const int PlayernameFieldNumber = 1;
    private string playername_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Playername {
      get { return playername_; }
      set {
        playername_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Playername != other.Playername) return false;
      if (Message != other.Message) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Playername.Length != 0) hash ^= Playername.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Playername.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Playername);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Playername.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Playername);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatPack other) {
      if (other == null) {
        return;
      }
      if (other.Playername.Length != 0) {
        Playername = other.Playername;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.State != 0) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Playername = input.ReadString();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            State = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LoginPack : pb::IMessage<LoginPack> {
    private static readonly pb::MessageParser<LoginPack> _parser = new pb::MessageParser<LoginPack>(() => new LoginPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginPack(LoginPack other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginPack Clone() {
      return new LoginPack(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginPack other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RoomPack : pb::IMessage<RoomPack> {
    private static readonly pb::MessageParser<RoomPack> _parser = new pb::MessageParser<RoomPack>(() => new RoomPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RoomPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomPack(RoomPack other) : this() {
      roomid_ = other.roomid_;
      maxnum_ = other.maxnum_;
      curnum_ = other.curnum_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomPack Clone() {
      return new RoomPack(this);
    }

    /// <summary>Field number for the "roomid" field.</summary>
    public const int RoomidFieldNumber = 1;
    private string roomid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Roomid {
      get { return roomid_; }
      set {
        roomid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "maxnum" field.</summary>
    public const int MaxnumFieldNumber = 2;
    private int maxnum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Maxnum {
      get { return maxnum_; }
      set {
        maxnum_ = value;
      }
    }

    /// <summary>Field number for the "curnum" field.</summary>
    public const int CurnumFieldNumber = 3;
    private int curnum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Curnum {
      get { return curnum_; }
      set {
        curnum_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 4;
    private global::SocketProto.RoomState state_ = global::SocketProto.RoomState.RoomNormal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.RoomState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RoomPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RoomPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Roomid != other.Roomid) return false;
      if (Maxnum != other.Maxnum) return false;
      if (Curnum != other.Curnum) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Roomid.Length != 0) hash ^= Roomid.GetHashCode();
      if (Maxnum != 0) hash ^= Maxnum.GetHashCode();
      if (Curnum != 0) hash ^= Curnum.GetHashCode();
      if (State != global::SocketProto.RoomState.RoomNormal) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Roomid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Roomid);
      }
      if (Maxnum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Maxnum);
      }
      if (Curnum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Curnum);
      }
      if (State != global::SocketProto.RoomState.RoomNormal) {
        output.WriteRawTag(32);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Roomid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Roomid);
      }
      if (Maxnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Maxnum);
      }
      if (Curnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Curnum);
      }
      if (State != global::SocketProto.RoomState.RoomNormal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RoomPack other) {
      if (other == null) {
        return;
      }
      if (other.Roomid.Length != 0) {
        Roomid = other.Roomid;
      }
      if (other.Maxnum != 0) {
        Maxnum = other.Maxnum;
      }
      if (other.Curnum != 0) {
        Curnum = other.Curnum;
      }
      if (other.State != global::SocketProto.RoomState.RoomNormal) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Roomid = input.ReadString();
            break;
          }
          case 16: {
            Maxnum = input.ReadInt32();
            break;
          }
          case 24: {
            Curnum = input.ReadInt32();
            break;
          }
          case 32: {
            State = (global::SocketProto.RoomState) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BattlePlayerPack : pb::IMessage<BattlePlayerPack> {
    private static readonly pb::MessageParser<BattlePlayerPack> _parser = new pb::MessageParser<BattlePlayerPack>(() => new BattlePlayerPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattlePlayerPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePlayerPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePlayerPack(BattlePlayerPack other) : this() {
      id_ = other.id_;
      teamid_ = other.teamid_;
      roomid_ = other.roomid_;
      playername_ = other.playername_;
      hero_ = other.hero_;
      battleid_ = other.battleid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePlayerPack Clone() {
      return new BattlePlayerPack(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "teamid" field.</summary>
    public const int TeamidFieldNumber = 2;
    private int teamid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Teamid {
      get { return teamid_; }
      set {
        teamid_ = value;
      }
    }

    /// <summary>Field number for the "roomid" field.</summary>
    public const int RoomidFieldNumber = 3;
    private int roomid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Roomid {
      get { return roomid_; }
      set {
        roomid_ = value;
      }
    }

    /// <summary>Field number for the "playername" field.</summary>
    public const int PlayernameFieldNumber = 4;
    private string playername_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Playername {
      get { return playername_; }
      set {
        playername_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hero" field.</summary>
    public const int HeroFieldNumber = 5;
    private global::SocketProto.Hero hero_ = global::SocketProto.Hero.XueLi;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.Hero Hero {
      get { return hero_; }
      set {
        hero_ = value;
      }
    }

    /// <summary>Field number for the "battleid" field.</summary>
    public const int BattleidFieldNumber = 6;
    private int battleid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Battleid {
      get { return battleid_; }
      set {
        battleid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattlePlayerPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattlePlayerPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Teamid != other.Teamid) return false;
      if (Roomid != other.Roomid) return false;
      if (Playername != other.Playername) return false;
      if (Hero != other.Hero) return false;
      if (Battleid != other.Battleid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Teamid != 0) hash ^= Teamid.GetHashCode();
      if (Roomid != 0) hash ^= Roomid.GetHashCode();
      if (Playername.Length != 0) hash ^= Playername.GetHashCode();
      if (Hero != global::SocketProto.Hero.XueLi) hash ^= Hero.GetHashCode();
      if (Battleid != 0) hash ^= Battleid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Teamid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Teamid);
      }
      if (Roomid != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Roomid);
      }
      if (Playername.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Playername);
      }
      if (Hero != global::SocketProto.Hero.XueLi) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Hero);
      }
      if (Battleid != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Battleid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Teamid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Teamid);
      }
      if (Roomid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Roomid);
      }
      if (Playername.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Playername);
      }
      if (Hero != global::SocketProto.Hero.XueLi) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Hero);
      }
      if (Battleid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Battleid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattlePlayerPack other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Teamid != 0) {
        Teamid = other.Teamid;
      }
      if (other.Roomid != 0) {
        Roomid = other.Roomid;
      }
      if (other.Playername.Length != 0) {
        Playername = other.Playername;
      }
      if (other.Hero != global::SocketProto.Hero.XueLi) {
        Hero = other.Hero;
      }
      if (other.Battleid != 0) {
        Battleid = other.Battleid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Teamid = input.ReadInt32();
            break;
          }
          case 24: {
            Roomid = input.ReadInt32();
            break;
          }
          case 34: {
            Playername = input.ReadString();
            break;
          }
          case 40: {
            Hero = (global::SocketProto.Hero) input.ReadEnum();
            break;
          }
          case 48: {
            Battleid = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FriendRoomPack : pb::IMessage<FriendRoomPack> {
    private static readonly pb::MessageParser<FriendRoomPack> _parser = new pb::MessageParser<FriendRoomPack>(() => new FriendRoomPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendRoomPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendRoomPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendRoomPack(FriendRoomPack other) : this() {
      roomid_ = other.roomid_;
      maxnum_ = other.maxnum_;
      curnum_ = other.curnum_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendRoomPack Clone() {
      return new FriendRoomPack(this);
    }

    /// <summary>Field number for the "roomid" field.</summary>
    public const int RoomidFieldNumber = 1;
    private string roomid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Roomid {
      get { return roomid_; }
      set {
        roomid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "maxnum" field.</summary>
    public const int MaxnumFieldNumber = 2;
    private int maxnum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Maxnum {
      get { return maxnum_; }
      set {
        maxnum_ = value;
      }
    }

    /// <summary>Field number for the "curnum" field.</summary>
    public const int CurnumFieldNumber = 3;
    private int curnum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Curnum {
      get { return curnum_; }
      set {
        curnum_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 4;
    private global::SocketProto.RoomState state_ = global::SocketProto.RoomState.RoomNormal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.RoomState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendRoomPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendRoomPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Roomid != other.Roomid) return false;
      if (Maxnum != other.Maxnum) return false;
      if (Curnum != other.Curnum) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Roomid.Length != 0) hash ^= Roomid.GetHashCode();
      if (Maxnum != 0) hash ^= Maxnum.GetHashCode();
      if (Curnum != 0) hash ^= Curnum.GetHashCode();
      if (State != global::SocketProto.RoomState.RoomNormal) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Roomid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Roomid);
      }
      if (Maxnum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Maxnum);
      }
      if (Curnum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Curnum);
      }
      if (State != global::SocketProto.RoomState.RoomNormal) {
        output.WriteRawTag(32);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Roomid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Roomid);
      }
      if (Maxnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Maxnum);
      }
      if (Curnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Curnum);
      }
      if (State != global::SocketProto.RoomState.RoomNormal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendRoomPack other) {
      if (other == null) {
        return;
      }
      if (other.Roomid.Length != 0) {
        Roomid = other.Roomid;
      }
      if (other.Maxnum != 0) {
        Maxnum = other.Maxnum;
      }
      if (other.Curnum != 0) {
        Curnum = other.Curnum;
      }
      if (other.State != global::SocketProto.RoomState.RoomNormal) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Roomid = input.ReadString();
            break;
          }
          case 16: {
            Maxnum = input.ReadInt32();
            break;
          }
          case 24: {
            Curnum = input.ReadInt32();
            break;
          }
          case 32: {
            State = (global::SocketProto.RoomState) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerPack : pb::IMessage<PlayerPack> {
    private static readonly pb::MessageParser<PlayerPack> _parser = new pb::MessageParser<PlayerPack>(() => new PlayerPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketProto.SocketProtoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerPack(PlayerPack other) : this() {
      username_ = other.username_;
      playername_ = other.playername_;
      id_ = other.id_;
      state_ = other.state_;
      hero_ = other.hero_;
      fightpattern_ = other.fightpattern_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerPack Clone() {
      return new PlayerPack(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playername" field.</summary>
    public const int PlayernameFieldNumber = 2;
    private string playername_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Playername {
      get { return playername_; }
      set {
        playername_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 4;
    private global::SocketProto.PlayerState state_ = global::SocketProto.PlayerState.PlayerOnline;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.PlayerState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "hero" field.</summary>
    public const int HeroFieldNumber = 5;
    private global::SocketProto.Hero hero_ = global::SocketProto.Hero.XueLi;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.Hero Hero {
      get { return hero_; }
      set {
        hero_ = value;
      }
    }

    /// <summary>Field number for the "fightpattern" field.</summary>
    public const int FightpatternFieldNumber = 6;
    private global::SocketProto.FightPattern fightpattern_ = global::SocketProto.FightPattern.BaoShiZhengBa;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SocketProto.FightPattern Fightpattern {
      get { return fightpattern_; }
      set {
        fightpattern_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Playername != other.Playername) return false;
      if (Id != other.Id) return false;
      if (State != other.State) return false;
      if (Hero != other.Hero) return false;
      if (Fightpattern != other.Fightpattern) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Playername.Length != 0) hash ^= Playername.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (State != global::SocketProto.PlayerState.PlayerOnline) hash ^= State.GetHashCode();
      if (Hero != global::SocketProto.Hero.XueLi) hash ^= Hero.GetHashCode();
      if (Fightpattern != global::SocketProto.FightPattern.BaoShiZhengBa) hash ^= Fightpattern.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Playername.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Playername);
      }
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Id);
      }
      if (State != global::SocketProto.PlayerState.PlayerOnline) {
        output.WriteRawTag(32);
        output.WriteEnum((int) State);
      }
      if (Hero != global::SocketProto.Hero.XueLi) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Hero);
      }
      if (Fightpattern != global::SocketProto.FightPattern.BaoShiZhengBa) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Fightpattern);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Playername.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Playername);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (State != global::SocketProto.PlayerState.PlayerOnline) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (Hero != global::SocketProto.Hero.XueLi) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Hero);
      }
      if (Fightpattern != global::SocketProto.FightPattern.BaoShiZhengBa) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Fightpattern);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerPack other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Playername.Length != 0) {
        Playername = other.Playername;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.State != global::SocketProto.PlayerState.PlayerOnline) {
        State = other.State;
      }
      if (other.Hero != global::SocketProto.Hero.XueLi) {
        Hero = other.Hero;
      }
      if (other.Fightpattern != global::SocketProto.FightPattern.BaoShiZhengBa) {
        Fightpattern = other.Fightpattern;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Playername = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt32();
            break;
          }
          case 32: {
            State = (global::SocketProto.PlayerState) input.ReadEnum();
            break;
          }
          case 40: {
            Hero = (global::SocketProto.Hero) input.ReadEnum();
            break;
          }
          case 48: {
            Fightpattern = (global::SocketProto.FightPattern) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
